### ISSUE TITLE
添加tg bot 后一直失败  reason: getaddrinfo EAI_AGAIN api.telegram.org

### ISSUE THREAD

**Issue by fcying** [cokemine/nodestatus#66]
装的最新的docker版本. 
命令行直接用这个token 是可以的
```
$ curl https://api.telegram.org/bot1955089157:AAG6wCsxMM_yjR7Su-ivqhchItfE_IaFUV8/getMe
{"ok":true,"result":{"id":1955089157,"is_bot":true,"first_name":"test","username":"fcying_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":true}}
```

运行后 看docker的log tg bot报错
```
nodestatus    | [2021-12-10T13:43:39.076] [INFO] default - 🎉  NodeStatus is listening on http://127.0.0.1:35601

nodestatus    | /app/node_modules/.pnpm/node-fetch@2.6.5/node_modules/node-fetch/lib/index.js:1483
nodestatus    |                         reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
nodestatus    |                                ^
nodestatus    | FetchError: request to https://api.telegram.org/bot1955089157:[REDACTED]/getMe failed, reason: getaddrinfo EAI_AGAIN api.telegram.org
nodestatus    |     at ClientRequest.<anonymous> (/app/node_modules/.pnpm/node-fetch@2.6.5/node_modules/node-fetch/lib/index.js:1483:11)
nodestatus    |     at ClientRequest.emit (node:events:390:28)
nodestatus    |     at TLSSocket.socketErrorListener (node:_http_client:447:9)
nodestatus    |     at TLSSocket.emit (node:events:390:28)
nodestatus    |     at emitErrorNT (node:internal/streams/destroy:157:8)
nodestatus    |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
nodestatus    |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
nodestatus    |   type: 'system',
nodestatus    |   errno: 'EAI_AGAIN',
nodestatus    |   code: 'EAI_AGAIN'
nodestatus    | }
```

dockerfile
```
version: "3"
services:
  nodestatus:
    image: cokemine/nodestatus
    container_name: nodestatus
    restart: always

    environment:
      PORT: 35601
      VERBOSE: "false"
      THEME: "hotaru-theme"

      USE_PUSH: "true"
      USE_IPC: "false"
      USE_WEB: "true"

      WEB_USERNAME: "test"
      WEB_PASSWORD: "test"
      WEB_SECRET: ""

      PUSH_TIMEOUT: 30
      PUSH_DELAY: 15
      TGBOT_TOKEN: "1955089157:AAG6wCsxMM_yjR7Su-ivqhchItfE_IaFUV8"
      TGBOT_CHATID: ""
      TGBOT_PROXY: ""
      TGBOT_WEBHOOK: ""

    volumes:
      - /usr/local/NodeStatus/server:/usr/local/NodeStatus/server
      - /tmp:/tmp:rw

    ports:
      - "35601:35601"
```

是不是tg bot 还要设置什么东西?
